services:
  postgres:
    image: postgres:16
    container_name: postgres-sales
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME:-dbSales}
      POSTGRES_USER: ${POSTGRES_USER:-sa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-DefaultPassword}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0.13
    container_name: sales_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: